language: java

script: 
  - cd jVTLlib
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cd9ad92f-bc13-444c-88b3-14b42740b3d3 || echo "Codecov did not collect coverage reports"
